### ISSUE TITLE
rmagick not installing

### ISSUE THREAD

**Issue by dinesh1988** [aviabird/angularspree-api#14]
Please help me to resolve this.

An error occurred while installing rmagick (2.16.0), and Bundler cannot
continue.
Make sure that gem install rmagick -v '2.16.0' succeeds before bundling.

In Gemfile:
rmagick

**Comment by pkrawat1** [comment]
please install image magic as the dependency library for this gem on your system first.

**Comment by dinesh1988** [comment]
Thanks for responding. I have the image magick installed but still rmagic is not installing.

**Comment by dinesh1988** [comment]
vendor/ruby-2.3.7/lib/ruby/2.3.0/webrick/server.rb:314:in `block in start_thread'

I get this if run in Heroku
